/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.problema.programacion.lineal;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mycompany.problema.programacion.lineal.parser.ParserLP;
import com.mycompany.problema.programacion.lineal.algoritmos.MetodoPL;

/**
 *
 * @author PC-ANDERSON
 */
public class MetodoGrafico extends javax.swing.JFrame implements MetodoPL {

    /**
     * Creates new form MetodoGrafico
     */
    
    @Override
    public void resolver(String FO, String[] R, String tipo) {
        calculos(FO, R, tipo);
    }

    @Override
    public void mostrar() {
        setVisible(true);
    }

    public MetodoGrafico() {
        initComponents();
        Recursos.aplicarIcono(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grafico = new com.mycompany.problema.programacion.lineal.GraficoPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grafico");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(712, 460));
        setResizable(false);

        grafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout graficoLayout = new javax.swing.GroupLayout(grafico);
        grafico.setLayout(graficoLayout);
        graficoLayout.setHorizontalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graficoLayout.setVerticalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtResultado.setLineWrap(true);
        txtResultado.setRows(4);
        txtResultado.setText("Aún no se ha calculado ninguna solución.");
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoGrafico().setVisible(true);
            }
        });
    }

    public void calculos(String FO, String[] R, String Tipo) {

        ParserLP.validarVariablesCompletas(FO, R);

        double[] Z = buildZmat(FO);
        double[][] Rmat = buildRmat(R, Z.length);

        if (Z.length != 2) {
            grafico.limpiar();
            txtResultado.setText("El método gráfico solo aplica a problemas con 2 variables (x1, x2).");
            return;
        }

        // Intersecciones con los ejes
        double[][] interceptos = new double[Rmat.length][2];

        List<double[]> vertices = new ArrayList<>();

        //==========================
        // Interceptos
        //==========================
        for (int i = 0; i < Rmat.length; i++) {

            double a = Rmat[i][0];
            double b = Rmat[i][1];
            double c = Rmat[i][2];

            interceptos[i][0] = (a != 0) ? c / a : Double.NaN;
            interceptos[i][1] = (b != 0) ? c / b : Double.NaN;
        }

        // Agregar origen
        vertices.add(new double[]{0, 0});

        // Agregar cortes con los ejes
        for (int i = 0; i < interceptos.length; i++) {

            if (!Double.isNaN(interceptos[i][0])) {
                vertices.add(new double[]{interceptos[i][0], 0});
            }

            if (!Double.isNaN(interceptos[i][1])) {
                vertices.add(new double[]{0, interceptos[i][1]});
            }
        }

        //==========================
        // Intersección entre rectas
        //==========================
        for (int i = 0; i < Rmat.length - 1; i++) {

            for (int j = i + 1; j < Rmat.length; j++) {

                double a1 = Rmat[i][0];
                double b1 = Rmat[i][1];
                double c1 = Rmat[i][2];

                double a2 = Rmat[j][0];
                double b2 = Rmat[j][1];
                double c2 = Rmat[j][2];

                double D = a1 * b2 - a2 * b1;

                if (Math.abs(D) < 1e-9) {
                    continue;
                }

                double x = (c1 * b2 - c2 * b1) / D;
                double y = (a1 * c2 - a2 * c1) / D;

                vertices.add(new double[]{x, y});
            }
        }

        //==========================
        // Eliminar duplicados
        //==========================
        List<double[]> verticesUnicos = new ArrayList<>();

        for (double[] p : vertices) {

            boolean existe = false;

            for (double[] q : verticesUnicos) {

                if (Math.abs(p[0] - q[0]) < 1e-6
                        && Math.abs(p[1] - q[1]) < 1e-6) {

                    existe = true;
                    break;
                }
            }

            if (!existe) {
                verticesUnicos.add(p);
            }
        }

        //==========================
        // Validar puntos
        //==========================
        List<double[]> puntosValidos = new ArrayList<>();
        List<Double> zvalues = new ArrayList<>();

        for (double[] punto : verticesUnicos) {

            double x = punto[0];
            double y = punto[1];

            // Región válida solo si x >= 0, y >= 0 (no negatividad)
            if (x < -1e-9 || y < -1e-9) {
                continue;
            }

            boolean valido = true;

            for (int i = 0; i < Rmat.length; i++) {

                double a = Rmat[i][0];
                double b = Rmat[i][1];
                double c = Rmat[i][2];
                int tipo = (int) Rmat[i][3];

                double resultado = a * x + b * y;

                switch (tipo) {

                    case 0: // <=
                        if (resultado > c + 1e-9) {
                            valido = false;
                        }
                        break;

                    case 1: // >=
                        if (resultado < c - 1e-9) {
                            valido = false;
                        }
                        break;

                    case 2: // =
                        if (Math.abs(resultado - c) > 1e-9) {
                            valido = false;
                        }
                        break;
                }

                if (!valido) {
                    break;
                }
            }

            if (valido) {

                puntosValidos.add(punto);

                double Zvalue = Z[0] * x + Z[1] * y;

                zvalues.add(Zvalue);
            }
        }

        //==========================
        // Buscar solución óptima
        //==========================
        double mejorZ;
        double[] mejorPunto = null;

        if (Tipo.equalsIgnoreCase("Max")) {
            mejorZ = Double.NEGATIVE_INFINITY;
        } else {
            mejorZ = Double.POSITIVE_INFINITY;
        }

        for (int i = 0; i < zvalues.size(); i++) {

            double valor = zvalues.get(i);

            if (Tipo.equalsIgnoreCase("Max")) {

                if (valor > mejorZ) {
                    mejorZ = valor;
                    mejorPunto = puntosValidos.get(i);
                }

            } else {

                if (valor < mejorZ) {
                    mejorZ = valor;
                    mejorPunto = puntosValidos.get(i);
                }
            }
        }

        //==========================
        // Resultado
        //==========================
        boolean esMax = Tipo.equalsIgnoreCase("Max");
        if (mejorPunto != null && esIlimitado(Rmat, Z, esMax)) {

            grafico.mostrarResultado(Rmat, null, null, 0, false);
            txtResultado.setText(esMax
                    ? "El problema no tiene solución acotada: Z crece indefinidamente dentro de la región factible."
                    : "El problema no tiene solución acotada: Z decrece indefinidamente dentro de la región factible.");

        } else if (mejorPunto != null) {

            List<double[]> poligono = ordenarPoligono(puntosValidos);
            grafico.mostrarResultado(Rmat, poligono, mejorPunto, mejorZ, true);

            txtResultado.setText(String.format(
                    "Solución óptima:   \nx1 = %.3f    \nx2 = %.3f    \nZ = %.3f",
                    mejorPunto[0], mejorPunto[1], mejorZ));

        } else {

            grafico.mostrarResultado(Rmat, null, null, 0, false);
            txtResultado.setText("No existe región factible para este problema.");
        }

    }

    /**
     * Ordena los vértices de la región factible por ángulo alrededor de su
     * centroide, para poder dibujar el polígono sombreado correctamente
     * (la región factible de un problema lineal siempre es convexa).
     */
    /**
     * Detecta si la región factible se extiende sin límite en alguna
     * dirección donde Z sigue mejorando: prueba varias direcciones dentro
     * del primer cuadrante (x,y &gt;= 0) y revisa si un punto muy lejano en
     * esa dirección sigue siendo factible. El método gráfico solo evalúa
     * un conjunto finito de vértices candidatos, así que sin esta
     * comprobación reportaría el mejor de esos vértices como si fuera el
     * óptimo real, aunque la región siga creciendo más allá.
     */
    private boolean esIlimitado(double[][] Rmat, double[] Z, boolean esMax) {
        for (int grados = 0; grados <= 90; grados += 5) {
            double rad = Math.toRadians(grados);
            double dx = Math.cos(rad);
            double dy = Math.sin(rad);

            double cDotD = Z[0] * dx + Z[1] * dy;
            boolean mejora = esMax ? cDotD > 1e-9 : cDotD < -1e-9;
            if (!mejora) {
                continue;
            }

            double lejano = 1e7;
            double x = dx * lejano;
            double y = dy * lejano;

            boolean factible = true;
            for (double[] r : Rmat) {
                double a = r[0];
                double b = r[1];
                double c = r[2];
                int tipo = (int) r[3];
                double resultado = a * x + b * y;

                switch (tipo) {
                    case 0 -> { // <=
                        if (resultado > c + 1e-6) {
                            factible = false;
                        }
                    }
                    case 1 -> { // >=
                        if (resultado < c - 1e-6) {
                            factible = false;
                        }
                    }
                    case 2 -> { // =
                        if (Math.abs(resultado - c) > 1e-6) {
                            factible = false;
                        }
                    }
                }
                if (!factible) {
                    break;
                }
            }
            if (factible) {
                return true;
            }
        }
        return false;
    }

    private List<double[]> ordenarPoligono(List<double[]> puntos) {
        if (puntos.size() < 3) {
            return puntos;
        }
        double cx = 0;
        double cy = 0;
        for (double[] p : puntos) {
            cx += p[0];
            cy += p[1];
        }
        cx /= puntos.size();
        cy /= puntos.size();

        List<double[]> ordenado = new ArrayList<>(puntos);
        double centroX = cx;
        double centroY = cy;
        ordenado.sort((p1, p2) -> {
            double a1 = Math.atan2(p1[1] - centroY, p1[0] - centroX);
            double a2 = Math.atan2(p2[1] - centroY, p2[0] - centroX);
            return Double.compare(a1, a2);
        });
        return ordenado;
    }

    private double[] buildZmat(String FO) {
        String limpio = FO.replaceAll("\\s+", "");
        Map<Integer, Double> coefs = ParserLP.parsearTerminos(limpio);

        int maxVar = 0;
        for (int idx : coefs.keySet()) {
            maxVar = Math.max(maxVar, idx);
        }

        double[] Z = new double[maxVar];
        for (Map.Entry<Integer, Double> e : coefs.entrySet()) {
            Z[e.getKey() - 1] = e.getValue();
        }
        return Z;
    }

    private double[][] buildRmat(String[] R, int numVars) {
        int maxVar = numVars;
        for (String restriccion : R) {
            String lhs = ParserLP.partirRestriccion(restriccion)[0];
            for (int idx : ParserLP.parsearTerminos(lhs).keySet()) {
                maxVar = Math.max(maxVar, idx);
            }
        }

        // variables + constante + tipo
        double[][] Rmat = new double[R.length][maxVar + 2];

        for (int i = 0; i < R.length; i++) {
            String[] partes = ParserLP.partirRestriccion(R[i]);
            String operador = partes[1];
            String derecha = partes[2];

            Map<Integer, Double> coefs = ParserLP.parsearTerminos(partes[0]);
            for (Map.Entry<Integer, Double> e : coefs.entrySet()) {
                Rmat[i][e.getKey() - 1] = e.getValue();
            }

            // término independiente
            Rmat[i][maxVar] = Double.parseDouble(derecha);

            // tipo de restricción
            switch (operador) {

                case "<=" ->
                    Rmat[i][maxVar + 1] = 0;

                case ">=" ->
                    Rmat[i][maxVar + 1] = 1;

                case "=" ->
                    Rmat[i][maxVar + 1] = 2;
            }
        }

        return Rmat;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.problema.programacion.lineal.GraficoPanel grafico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
