/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.problema.programacion.lineal;

import java.util.Arrays;
import javax.swing.JOptionPane;
import java.util.regex.*;
import java.util.*;
import com.mycompany.problema.programacion.lineal.parser.ParserLP;
import com.mycompany.problema.programacion.lineal.algoritmos.MetodoPL;

/**
 *
 * @author PC-ANDERSON
 */
public class PrincipalPage extends javax.swing.JFrame {

    private String Fo;
    private String[] R;

    /**
     * Creates new form PrincipalPage
     */
    public PrincipalPage() {
        initComponents();
        Recursos.aplicarIcono(this);
        ObjetiveFunction.setSoloUnaLinea(true);
        ObjetiveFunction.setBackground(java.awt.Color.WHITE);
        jScrollPane3.getViewport().setBackground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblLogo = new javax.swing.JLabel(Recursos.obtenerLogoEscalado(150));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ZType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Restrictions = new SubIndiceTextPane();
        jLabel3 = new javax.swing.JLabel();
        AlgoritmoBox = new javax.swing.JComboBox<>();
        CalcButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ObjetiveFunction = new SubIndiceTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vertex — Programación Lineal");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 60, 110));
        jLabel1.setText("Z");

        ZType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Max", "Min" }));
        ZType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZTypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 60, 110));
        jLabel2.setText("Sujeto a:");

        Restrictions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RestrictionsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Restrictions);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 60, 110));
        jLabel3.setText("Algoritmo:");

        AlgoritmoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decide por mi", "Grafico", "Numerico", "Simplex", "Big M", "Simplex Dual", "Costos Dual", "Hungaro" }));

        CalcButton.setBackground(new java.awt.Color(51, 102, 204));
        CalcButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        CalcButton.setForeground(java.awt.Color.WHITE);
        CalcButton.setFocusPainted(false);
        CalcButton.setText("Calcular");
        CalcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcButtonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 60, 110));
        jLabel4.setText("=");

        ObjetiveFunction.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ObjetiveFunction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ObjetiveFunctionKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(ObjetiveFunction);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblLogo)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ZType, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(AlgoritmoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLogo)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ZType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, 38, 38, 38))
                    .addGap(33, 33, 33)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AlgoritmoBox)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jPanel1, gridBagConstraints);
        getContentPane().setBackground(java.awt.Color.WHITE);
        jPanel1.setBackground(java.awt.Color.WHITE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZTypeActionPerformed

    private void CalcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcButtonMouseClicked

        if ("".equals(ObjetiveFunction.getText()) || "".equals(Restrictions.getText())) {
            JOptionPane.showMessageDialog(null, "Llena todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        setFO(ObjetiveFunction.getText());
        setR(Restrictions.getText().split("\\r?\\n"));
        String FO = getFO();
        String[] R = getR();
        String tipo = ZType.getSelectedItem().toString();

        try {
            String[][] RMat = PrincipalPage.validateAndBuild(FO, R);

            System.out.println("Matriz de restricciones:");
            for (String[] fila : RMat) {
                System.out.println(Arrays.toString(fila));
            }

            //selección de metodo a usar
            int metodo;
            switch (AlgoritmoBox.getSelectedIndex()) {
                case 0:
                    // interpretar el algoritmo a usar según las características del problema
                    metodo = 0;
                    // 1. Algoritmo Húngaro → problema de asignación
                    // Condición: todas las restricciones del tipo ∑ xij = 1 (filas/columnas balanceadas, valores binarios)
                    if (checkHungaro(R, FO, metodo)) {
                        resolverYMostrar(new AlgoritmoHungaro(), FO, R, tipo);

                        // 2. Algoritmo de Costos Duales → transporte/distribución
                        // Condición: problema de transporte con oferta = demanda total
                    } else if (checkCostosDuales(R, FO, metodo)) {
                        resolverYMostrar(new AlgoritmoCostosDuales(), FO, R, tipo);

                        // 3. Método Dual Simplex
                        // Condición: solución inicial primal no factible pero dual sí factible
                    } else if (checkDualSimplex(R, FO, metodo)) {
                        resolverYMostrar(new AlgoritmoDual(), FO, R, tipo);

                        // 4. Método Gráfico
                        // Condición: 2 variables en FO y restricciones lineales
                    } else if (checkGrafico(R, FO, metodo)) {
                        resolverYMostrar(new MetodoGrafico(), FO, R, tipo);

                        // 5. Método Big-M
                        // Condición: existen restricciones con ≥ o = y término independiente ≠ 0
                    } else if (checkBigM(R, FO, metodo)) {
                        resolverYMostrar(new MetodoBigM(), FO, R, tipo);

                        // 6. Método Simplex
                        // Condición: siempre aplica, caso general
                    } else if (checkSimplex(R, FO, metodo)) {
                        resolverYMostrar(new MetodoSimplex(), FO, R, tipo);

                        // 7. Método Numérico (fallback)
                        // Condición: casos especiales o pruebas numéricas
                    } else {
                        resolverYMostrar(new MetodoNumerico(), FO, R, tipo);
                    }
                    //Decide por mi, Grafico, Numerico, Simplex, Big M, Simplex Dual, Costos Dual, Hungaro
                    break;
                case 1:
                    metodo = 1;
                    if (checkGrafico(R, FO, metodo)) {
                        resolverYMostrar(new MetodoGrafico(), FO, R, tipo);
                    } else {
                        ofrecerFallbackSimplex("El problema no cumple condiciones para un método especializado.", FO, R, tipo);
                    }
                    break;
                case 2:
                    metodo = 2;
                    resolverYMostrar(new MetodoNumerico(), FO, R, tipo);
                    break;
                case 3:
                    metodo = 3;
                    resolverYMostrar(new MetodoSimplex(), FO, R, tipo);
                    break;
                case 4:
                    metodo = 4;
                    if (checkBigM(R, FO, metodo)) {
                        resolverYMostrar(new MetodoBigM(), FO, R, tipo);
                    } else {
                        ofrecerFallbackSimplex("El problema no cumple condiciones para Big M.", FO, R, tipo);
                    }
                    break;
                case 5:
                    metodo = 5;
                    if (checkDualSimplex(R, FO, metodo)) {
                        resolverYMostrar(new AlgoritmoDual(), FO, R, tipo);
                    } else {
                        ofrecerFallbackSimplex("El problema no cumple condiciones para el Simplex Dual.", FO, R, tipo);
                    }
                    break;
                case 6:
                    metodo = 6;
                    resolverYMostrar(new AlgoritmoCostosDuales(), FO, R, tipo);
                    break;
                case 7:
                    metodo = 7;
                    resolverYMostrar(new AlgoritmoHungaro(), FO, R, tipo);
                    break;
                default:
                    break;
            }

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CalcButtonMouseClicked

    /**
     * Corre el algoritmo elegido y muestra su ventana. Al recibir un
     * {@link MetodoPL} en vez del tipo concreto, este método sirve para
     * cualquiera de las 7 ventanas sin necesidad de repetir
     * "new X(); x.calculos(...); x.show();" en cada rama del switch.
     */
    private void resolverYMostrar(MetodoPL metodo, String FO, String[] R, String tipo) {
        metodo.resolver(FO, R, tipo);
        metodo.mostrar();
    }

    /** Pregunta si se quiere resolver con Simplex cuando el método elegido no aplica, y lo corre si acepta. */
    private void ofrecerFallbackSimplex(String motivo, String FO, String[] R, String tipo) {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                motivo + "\n¿Desea resolverlo con Simplex?",
                "Sugerencia",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            resolverYMostrar(new MetodoSimplex(), FO, R, tipo);
        }
    }

    private void RestrictionsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RestrictionsKeyTyped
        //Validar que el key sea valido
        char c = evt.getKeyChar();
        String cc = String.valueOf(c);
        if (c == '\b' || c == '\n') {
            return;
        }

        if (!(cc.equals("X") || cc.equals("x") || Character.isDigit(c) || cc.equals("+") || cc.equals("-") || cc.equals("<") || cc.equals(">") || cc.equals("=") || cc.equals(".") || cc.equals("/"))) {
            evt.consume(); // cancela la tecla
            java.awt.Toolkit.getDefaultToolkit().beep(); // sonido error
        }
    }//GEN-LAST:event_RestrictionsKeyTyped

    @SuppressWarnings("empty-statement")
    private void ObjetiveFunctionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ObjetiveFunctionKeyTyped
        //validar que el key sea valido
        char c = evt.getKeyChar();
        String cc = String.valueOf(c);
        if (c == '\b' || c == '\n') {
            return;
        }

        if (!(cc.equals("X") || cc.equals("x") || Character.isDigit(c) || cc.equals("+") || cc.equals("-") || cc.equals(".") || cc.equals("/"))) {
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_ObjetiveFunctionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalPage().setVisible(true);
        });

    }

    public static String[][] validateAndBuild(String FO, String[] R) {
        if (FO == null || FO.trim().isEmpty() || R == null || R.length == 0) {
            throw new IllegalArgumentException("La función objetivo y las restricciones no pueden estar vacías.");
        }

        FO = FO.replaceAll("\\s+", "");
        for (int i = 0; i < R.length; i++) {
            R[i] = R[i].replaceAll("\\s+", "");
        }

        // Detectar variables en FO
        Pattern varPattern = Pattern.compile("x(\\d+)", Pattern.CASE_INSENSITIVE);
        Set<Integer> foVars = new HashSet<>();
        Set<Integer> restrVars = new HashSet<>();
        Set<Integer> formatos = new HashSet<>();

        Matcher mFO = varPattern.matcher(FO);
        while (mFO.find()) {
            foVars.add(Integer.valueOf(mFO.group(1)));
            formatos.add(mFO.group(1).length());
        }

        for (String restr : R) {
            Matcher mR = varPattern.matcher(restr);
            while (mR.find()) {
                restrVars.add(Integer.valueOf(mR.group(1)));
                formatos.add(mR.group(1).length());
            }
        }

        if (formatos.size() > 1) {
            throw new IllegalArgumentException("Inconsistencia en las variables: mezcla de índices con distinta longitud.");
        }

        // Variables definidas por FO (todas deben aparecer en FO)
        List<Integer> orderedVars = new ArrayList<>(foVars);
        Collections.sort(orderedVars);

        // Validar que ninguna restricción use variables fuera de FO
        for (int var : restrVars) {
            if (!foVars.contains(var)) {
                throw new IllegalArgumentException("Variable x" + var + " aparece en restricciones pero no en FO.");
            }
        }

        int Xn = orderedVars.size();
        String[][] RMat = new String[R.length][Xn + 2];

        // Procesar restricciones
        for (int i = 0; i < R.length; i++) {
            String restr = R[i];

            // Validar un operador
            Pattern opPattern = Pattern.compile("(<=|>=|=|<|>)");
            Matcher mOp = opPattern.matcher(restr);
            int count = 0;
            while (mOp.find()) {
                count++;
            }
            if (count != 1) {
                throw new IllegalArgumentException("La restricción " + (i + 1) + " no tiene exactamente un operador.");
            }

            // Dividir restricción
            String[] partes = parseRestriction(restr);
            String lhs = partes[0];
            String op = partes[1];
            String rhs = partes[2];

            // Validar RHS
            if (!rhs.matches("-?\\d+(\\.\\d+)?")) {
                throw new IllegalArgumentException("La restricción " + (i + 1) + " tiene un término independiente no numérico: " + rhs);
            }

            // Parsear coeficientes → mapa
            Map<Integer, String> coeffs = parseCoefficientsMap(lhs);

            // Rellenar fila
            for (int j = 0; j < Xn; j++) {
                int varIndex = orderedVars.get(j);
                RMat[i][j] = coeffs.getOrDefault(varIndex, "0");
            }
            RMat[i][Xn] = op;
            RMat[i][Xn + 1] = rhs;
        }

        return RMat;
    }

// Divide restricción en LHS, operador, RHS
    public static String[] parseRestriction(String restr) {
        return ParserLP.partirRestriccion(restr);
    }

// Convierte LHS en vector de coeficientes
    public static String[] parseCoefficients(String lhs, int Xn) {
        String[] coeffs = new String[Xn];
        Arrays.fill(coeffs, "0");
        Map<Integer, Double> parsed = ParserLP.parsearTerminos(lhs);
        for (Map.Entry<Integer, Double> e : parsed.entrySet()) {
            int index = e.getKey() - 1; // x1 → columna 0
            if (index >= 0 && index < Xn) {
                coeffs[index] = fmtCoef(e.getValue());
            }
        }
        return coeffs;
    }

    private static String fmtCoef(double v) {
        if (Math.abs(v - Math.round(v)) < 1e-9) {
            return String.valueOf(Math.round(v));
        }
        return String.valueOf(v);
    }

    public static Map<Integer, String> parseCoefficientsMap(String lhs) {
        Map<Integer, Double> parsed = ParserLP.parsearTerminos(lhs);
        Map<Integer, String> coeffs = new HashMap<>();
        for (Map.Entry<Integer, Double> e : parsed.entrySet()) {
            coeffs.put(e.getKey(), fmtCoef(e.getValue()));
        }
        return coeffs;
    }

// ---------------------------
// Checks avanzados de selección
// ---------------------------
    /**
     * Comprueba si el problema tiene estructura de asignación (húngaro).
     * Requisitos: - Las variables deben tener subíndice de longitud par (ej:
     * "ij" => length%2==0), se divide en 2 partes iguales (i, j). - Deben
     * existir restricciones igualdad (=) con RHS = 1 que correspondan a cada i
     * (fila) y cada j (columna), es decir: sum_j x_ij = 1 y sum_i x_ij = 1.
     */
    private boolean checkHungaro(String[] restricciones, String FO, int metodo) {
        Pattern varPattern = Pattern.compile("x(\\d+)", Pattern.CASE_INSENSITIVE);

        Matcher mFO = varPattern.matcher(FO);
        if (!mFO.find()) {
            return metodo != 0 ? pair(metodo, FO, restricciones) : false;
        }

        int idxLen = mFO.group(1).length();
        if (idxLen % 2 != 0) {
            return metodo != 0 ? pair(metodo, FO, restricciones) : false;
        }

        int subLen = idxLen / 2;
        Set<String> firstSet = new HashSet<>();
        Set<String> secondSet = new HashSet<>();
        mFO = varPattern.matcher(FO);
        while (mFO.find()) {
            String digits = mFO.group(1);
            if (digits.length() != idxLen) {
                return metodo != 0 ? pair(metodo, FO, restricciones) : false;
            }
            firstSet.add(digits.substring(0, subLen));
            secondSet.add(digits.substring(subLen));
        }

        // buscar restricciones tipo "xij + ... = 1"
        Set<String> foundRows = new HashSet<>();
        Set<String> foundCols = new HashSet<>();
        Pattern termPattern = Pattern.compile("([+-]?\\d*\\.?\\d*)x(\\d+)", Pattern.CASE_INSENSITIVE);

        for (String r : restricciones) {
            String[] partes = parseRestriction(r);
            String lhs = partes[0], op = partes[1], rhs = partes[2];

            if (!op.equals("=") || !rhs.equals("1")) {
                continue;
            }

            Matcher tm = termPattern.matcher(lhs);
            Set<String> rowIdxs = new HashSet<>();
            Set<String> colIdxs = new HashSet<>();
            boolean allCoeffsOne = true;

            while (tm.find()) {
                String coefStr = tm.group(1);
                String digits = tm.group(2);
                if (digits.length() != idxLen) {
                    allCoeffsOne = false;
                    break;
                }

                if (!(coefStr == null || coefStr.isEmpty() || coefStr.equals("+"))) {
                    try {
                        if (Math.abs(Double.parseDouble(coefStr) - 1.0) > 1e-9) {
                            allCoeffsOne = false;
                            break;
                        }
                    } catch (NumberFormatException ex) {
                        allCoeffsOne = false;
                        break;
                    }
                }

                rowIdxs.add(digits.substring(0, subLen));
                colIdxs.add(digits.substring(subLen));
            }

            if (!allCoeffsOne) {
                continue;
            }
            if (rowIdxs.size() == 1) {
                foundRows.addAll(rowIdxs);
            }
            if (colIdxs.size() == 1) {
                foundCols.addAll(colIdxs);
            }
        }

        boolean ok = foundRows.containsAll(firstSet) && foundCols.containsAll(secondSet);
        if (!ok && metodo != 0) {
            return pair(metodo, FO, restricciones);
        }

        return ok;
    }

    /**
     * Comprueba estructura de transporte / costos duales. Requisitos básicos
     * (heurísticos): - Variables xij con índice divisible en i,j (igual que
     * Hungaro). - Deben existir restricciones por cada origen (i) con RHS=num
     * (oferta) y por cada destino (j) con RHS=num (demanda). - suma(oferta) ==
     * suma(demanda).
     */
    private boolean checkCostosDuales(String[] restricciones, String FO, int metodo) {
        Pattern varPattern = Pattern.compile("x(\\d+)", Pattern.CASE_INSENSITIVE);

        Matcher mFO = varPattern.matcher(FO);
        if (!mFO.find()) {
            return false;
        }
        int idxLen = mFO.group(1).length();
        if (idxLen % 2 != 0) {
            return false; // debe dividirse en i y j
        }
        int subLen = idxLen / 2;

        // obtener sets de i y j desde FO
        Set<String> firstSet = new HashSet<>();
        Set<String> secondSet = new HashSet<>();
        mFO.reset();
        while (mFO.find()) {
            String digits = mFO.group(1);
            if (digits.length() != idxLen) {
                return false;
            }
            String a = digits.substring(0, subLen);
            String b = digits.substring(subLen);
            firstSet.add(a);
            secondSet.add(b);
        }

        // recorrer restricciones y clasificar como oferta (por i) o demanda (por j)
        Map<String, Double> oferta = new HashMap<>();
        Map<String, Double> demanda = new HashMap<>();
        Pattern termPattern = Pattern.compile("([+-]?\\d*\\.?\\d*)x(\\d+)", Pattern.CASE_INSENSITIVE);

        for (String r : restricciones) {
            String[] partes = parseRestriction(r);
            String lhs = partes[0];
            String op = partes[1];
            String rhs = partes[2];

            double rhsVal;
            try {
                rhsVal = Double.parseDouble(rhs);
            } catch (NumberFormatException ex) {
                continue;
            }

            Matcher tm = termPattern.matcher(lhs);
            Set<String> rowIdxs = new HashSet<>();
            Set<String> colIdxs = new HashSet<>();
            while (tm.find()) {
                String digits = tm.group(2);
                if (digits.length() != idxLen) {
                    rowIdxs.clear();
                    colIdxs.clear();
                    break;
                }
                String a = digits.substring(0, subLen);
                String b = digits.substring(subLen);
                rowIdxs.add(a);
                colIdxs.add(b);
            }

            if (rowIdxs.size() == 1 && colIdxs.size() >= 1 && (op.equals("<=") || op.equals("="))) {
                oferta.put(rowIdxs.iterator().next(), rhsVal);
            } else if (colIdxs.size() == 1 && rowIdxs.size() >= 1 && op.equals("=")) {
                demanda.put(colIdxs.iterator().next(), rhsVal);
            }
        }

        if (!oferta.keySet().containsAll(firstSet)) {
            return false;
        }
        if (!demanda.keySet().containsAll(secondSet)) {
            return false;
        }

        double sumOferta = oferta.values().stream().mapToDouble(Double::doubleValue).sum();
        double sumDemanda = demanda.values().stream().mapToDouble(Double::doubleValue).sum();

        // balancear si está en modo "seleccionado"
        if (metodo != 0 && Math.abs(sumOferta - sumDemanda) > 1e-9) {
            List<String> RArreglado = new ArrayList<>(Arrays.asList(restricciones));
            String nuevaFO = FO;

            if (sumOferta > sumDemanda) {
                double faltante = sumOferta - sumDemanda;
                String nuevaCol = "DF"; // demanda ficticia
                for (String fila : firstSet) {
                    String var = "x" + fila + nuevaCol;
                    nuevaFO = nuevaFO + " + 0" + var;
                }
                RArreglado.add("Σx_" + nuevaCol + " = " + faltante);
            } else {
                double faltante = sumDemanda - sumOferta;
                String nuevaFila = "OF"; // oferta ficticia
                for (String col : secondSet) {
                    String var = "x" + nuevaFila + col;
                    nuevaFO = nuevaFO + " + 0" + var;
                }
                RArreglado.add("Σx_" + nuevaFila + " = " + faltante);
            }

            setFO(nuevaFO);
            setR(RArreglado.toArray(new String[0]));
            return pair(metodo, nuevaFO, getR());
        }

        return Math.abs(sumOferta - sumDemanda) < 1e-9;
    }

    /**
     * Heurístico para detectar caso candidato a Dual Simplex. Actualmente: si
     * existe alguna restricción con RHS < 0 -> sugerir Dual Simplex. (Es un
     * heurístico simple; podemos mejorar con análisis de tabla inicial,
     * factibilidad, etc.)
     */
    private boolean checkDualSimplex(String[] restricciones, String FO, int metodo) {
    boolean hayNegativo = false;
    for (String r : restricciones) {
        String[] partes = parseRestriction(r); // [lhs, op, rhs]
        String rhs = partes[2];
        try {
            double val = Double.parseDouble(rhs);
            if (val < 0) {
                hayNegativo = true;
                break;
            }
        } catch (NumberFormatException ex) {
            // ignorar no numéricos
        }
    }

    if (metodo != 0) {
        return pair(metodo, FO, restricciones);
    }

    return hayNegativo; // heurístico: si hay RHS < 0 → sugerir Dual Simplex
}


// 4. Método Gráfico
    private boolean checkGrafico(String[] restricciones, String FO, int metodo) {
        // El método gráfico solo exige 2 variables de decisión. A diferencia
        // de Simplex/Big-M/Dual/etc, NO necesita transformar la FO ni las
        // restricciones (no usa holguras, excesos ni artificiales) porque
        // evalúa cada restricción tal cual (<=, >= o =) al validar los
        // vértices — por eso NO debe llamar a pair(), que no tiene un caso
        // para este método y por eso siempre devolvía false al elegirlo
        // manualmente. Tampoco debe descartar >= ni =, porque el gráfico
        // los soporta perfectamente (a diferencia de Big-M, que sí los
        // necesita para decidir si aplica).
        Pattern varPattern = Pattern.compile("x(\\d+)", Pattern.CASE_INSENSITIVE);
        Matcher m = varPattern.matcher(FO);
        Set<Integer> vars = new HashSet<>();
        while (m.find()) {
            vars.add(Integer.valueOf(m.group(1)));
        }
        return vars.size() == 2;
    }

    private boolean isZero(String s) {
        try {
            return Math.abs(Double.parseDouble(s.trim())) < 1e-9;
        } catch (NumberFormatException e) {
            return false;
        }
    }

// 5. Método Big-M
private boolean checkBigM(String[] restricciones, String FO, int metodo) {
    // Condición: restricciones con ≥ o = y RHS ≠ 0 → necesita artificiales
    for (String r : restricciones) {
        if (r.contains(">=") || (r.contains("=") && !r.trim().endsWith("0"))) {
            if (metodo == 0) {
                return true; // heurístico
            } else {
                return pair(metodo, FO, restricciones);
            }
        }
    }
    if (metodo != 0) {
        return pair(metodo, FO, restricciones);
    }
    return false;
}


// 6. Método Simplex Estándar
    private boolean checkSimplex(String[] restricciones, String FO, int metodo) {
        // Siempre válido, es el "catch-all"
        if (metodo != 0) {
            return pair(metodo, FO, restricciones);
        }
        return true;
    }

private boolean pair(int metodo, String FO, String[] R) {
    List<String> RArreglado;
    String nuevaFO;
    Pattern varPattern;
    Matcher mFO;
    int subLen;

    switch (metodo) {
        case 3: // Simplex: agregar holguras/excesos (y añadirlas a FO con coef 0)
            List<String> nuevasRestricciones = new ArrayList<>();
            String nuevaFOSB1 = FO == null ? "" : FO.trim();
            int holguraCount = 0;
            int excesoCount = 0;

            for (String r : R) {
                String[] partes = parseRestriction(r);
                String lhs = partes[0].trim();
                String op  = partes[1].trim();
                String rhs = partes[2].trim();

                if (op.equals("<=")) {
                    holguraCount++;
                    String sVar = "S" + holguraCount;
                    nuevasRestricciones.add(lhs + " + " + sVar + " = " + rhs);
                    nuevaFOSB1 = addZeroVarToFO(nuevaFOSB1, sVar);
                } else if (op.equals(">=")) {
                    excesoCount++;
                    String eVar = "E" + excesoCount;
                    nuevasRestricciones.add(lhs + " - " + eVar + " = " + rhs);
                    nuevaFOSB1 = addZeroVarToFO(nuevaFOSB1, eVar);
                } else { // '='
                    nuevasRestricciones.add(lhs + " = " + rhs);
                }
            }

            setR(nuevasRestricciones.toArray(new String[0]));
            setFO(nuevaFOSB1);
            return true;

        case 4: // Big-M: agregar artificiales y penalizarlas en FO con M*(A#)
            nuevasRestricciones = new ArrayList<>();
            StringBuilder nuevaFOSB = new StringBuilder(FO == null ? "" : FO.trim());
            int artificialCount = 0;

            for (String r : R) {
                String[] partes = parseRestriction(r);
                String lhs = partes[0].trim();
                String op  = partes[1].trim();
                String rhs = partes[2].trim();

                if (op.equals(">=") || (op.equals("=") && !isZero(rhs))) {
                    artificialCount++;
                    String artVar = "A" + artificialCount;
                    // Para >=: normalmente harías "- e + a = rhs", pero para simplificar
                    // convertimos a igualdad con artificial y (opcional) exceso
                    // Aquí agregamos la artificial directamente:
                    nuevasRestricciones.add(lhs + " + " + artVar + " = " + rhs);
                    // penalizar en FO: usar M*ArtVar (agrega como + M*A# ; si usas max/min, ajusta signo)
                    nuevaFOSB.append(" + M*").append(artVar);
                } else {
                    nuevasRestricciones.add(lhs + " " + op + " " + rhs);
                }
            }

            setR(nuevasRestricciones.toArray(new String[0]));
            setFO(nuevaFOSB.toString());
            return true;

        case 5: // Dual Simplex: invertir restricciones con RHS < 0 (negar LHS y RHS, invertir op)
            nuevasRestricciones = new ArrayList<>();
            for (String r : R) {
                String[] partes = parseRestriction(r);
                String lhs = partes[0].trim();
                String op  = partes[1].trim();
                String rhs = partes[2].trim();

                double val;
                try {
                    val = Double.parseDouble(rhs);
                } catch (NumberFormatException ex) {
                    nuevasRestricciones.add(lhs + " " + op + " " + rhs);
                    continue;
                }

                if (val < 0) {
                    String nuevoOp;
                    if (op.equals("<=")) nuevoOp = ">=";
                    else if (op.equals(">=")) nuevoOp = "<=";
                    else nuevoOp = op;

                    String nuevoLHS = negateLHS(lhs);
                    String nuevoRHS = String.valueOf(-val);
                    nuevasRestricciones.add(nuevoLHS + " " + nuevoOp + " " + nuevoRHS);
                } else {
                    nuevasRestricciones.add(lhs + " " + op + " " + rhs);
                }
            }
            setR(nuevasRestricciones.toArray(new String[0]));
            setFO(FO);
            return true;

        case 6: // Costos Dual: balancear oferta/demanda creando INDICES NUMÉRICOS nuevos
            // reconstruimos oferta/demanda igual que en check y, si hay diferencia, agregamos columnas/filas numericas
            varPattern = Pattern.compile("x(\\d+)", Pattern.CASE_INSENSITIVE);
            mFO = varPattern.matcher(FO);
            if (!mFO.find()) return false;
            int idxLen = mFO.group(1).length();
            if (idxLen % 2 != 0) return false;
            subLen = idxLen / 2;

            // obtener sets de i y j desde FO
            Set<String> firstSet = new LinkedHashSet<>();
            Set<String> secondSet = new LinkedHashSet<>();
            mFO.reset();
            while (mFO.find()) {
                String digits = mFO.group(1);
                if (digits.length() != idxLen) return false;
                String a = digits.substring(0, subLen);
                String b = digits.substring(subLen);
                firstSet.add(a); secondSet.add(b);
            }

            // armar mapas oferta/demanda
            Map<String, Double> oferta = new LinkedHashMap<>();
            Map<String, Double> demanda = new LinkedHashMap<>();
            Pattern termPattern = Pattern.compile("([+-]?\\d*\\.?\\d*)x(\\d+)", Pattern.CASE_INSENSITIVE);
            for (String r : R) {
                String[] partes = parseRestriction(r);
                String lhs = partes[0]; String op = partes[1]; String rhs = partes[2];
                double rhsVal;
                try { rhsVal = Double.parseDouble(rhs); } catch (NumberFormatException ex) { continue; }

                Matcher tm = termPattern.matcher(lhs);
                Set<String> rowIdxs = new HashSet<>(), colIdxs = new HashSet<>();
                while (tm.find()) {
                    String digits = tm.group(2);
                    if (digits.length() != idxLen) { rowIdxs.clear(); colIdxs.clear(); break; }
                    String a = digits.substring(0, subLen), b = digits.substring(subLen);
                    rowIdxs.add(a); colIdxs.add(b);
                }
                if (rowIdxs.size() == 1 && colIdxs.size() >= 1 && (op.equals("<=") || op.equals("="))) {
                    oferta.put(rowIdxs.iterator().next(), rhsVal);
                } else if (colIdxs.size() == 1 && rowIdxs.size() >= 1 && op.equals("=")) {
                    demanda.put(colIdxs.iterator().next(), rhsVal);
                }
            }

            if (!oferta.keySet().containsAll(firstSet) || !demanda.keySet().containsAll(secondSet)) {
                return false;
            }

            double sumOferta = oferta.values().stream().mapToDouble(Double::doubleValue).sum();
            double sumDemanda = demanda.values().stream().mapToDouble(Double::doubleValue).sum();
            if (Math.abs(sumOferta - sumDemanda) < 1e-9) return true;

            // decidir índices nuevos: usamos la mayor fila/col existente + k
            int[] maxRC = getMaxRowCol(FO);
            int maxRow = maxRC[0], maxCol = maxRC[1];

            RArreglado = new ArrayList<>(Arrays.asList(R));
            nuevaFO = FO;

            if (sumOferta > sumDemanda) {
                double faltante = sumOferta - sumDemanda;
                // crear 1 nueva columna con index = maxCol+1
                int newCol = maxCol + 1;
                String newColStr = String.format("%0" + (idxLen/2) + "d", newCol);
                for (String fila : firstSet) {
                    String varDigits = fila + newColStr;
                    String var = "x" + varDigits;
                    nuevaFO = addZeroVarToFO(nuevaFO, var);
                }
                // crear restriccion de la nueva columna: suma_i x(i,newCol)=faltante
                StringBuilder sb = new StringBuilder();
                boolean first = true;
                for (String fila : firstSet) {
                    if (!first) sb.append(" + ");
                    sb.append("x").append(fila).append(newColStr);
                    first = false;
                }
                sb.append(" = ").append(String.valueOf((long)faltante));
                RArreglado.add(sb.toString());
            } else {
                double faltante = sumDemanda - sumOferta;
                // crear 1 nueva fila con index = maxRow+1
                int newRow = maxRow + 1;
                String newRowStr = String.format("%0" + (idxLen/2) + "d", newRow);
                for (String col : secondSet) {
                    String varDigits = newRowStr + col;
                    String var = "x" + varDigits;
                    nuevaFO = addZeroVarToFO(nuevaFO, var);
                }
                // restricción de la nueva fila: suma_j x(newRow,j) = faltante
                StringBuilder sb = new StringBuilder();
                boolean first = true;
                for (String col : secondSet) {
                    if (!first) sb.append(" + ");
                    sb.append("x").append(newRowStr).append(col);
                    first = false;
                }
                sb.append(" = ").append(String.valueOf((long)faltante));
                RArreglado.add(sb.toString());
            }

            setFO(nuevaFO);
            setR(RArreglado.toArray(new String[0]));
            return true;

        case 7: // Hungaro: asegurar indices numéricos y crear columnas/filas numéricas
            varPattern = Pattern.compile("x(\\d+)", Pattern.CASE_INSENSITIVE);
            mFO = varPattern.matcher(FO);
            if (!mFO.find()) return false;
            int idx = mFO.group(1).length();
            if (idx % 2 != 0) return false; // no se puede dividir

            // recolectar sets
            Set<String> filas = new LinkedHashSet<>();
            Set<String> cols = new LinkedHashSet<>();
            mFO.reset();
            while (mFO.find()) {
                String subIndice = mFO.group(1);
                int subL = subIndice.length()/2;
                filas.add(subIndice.substring(0, subL));
                cols.add(subIndice.substring(subL));
            }

            int difer = filas.size() - cols.size();
            if (difer == 0) return true;

            // decidir max indices
            int[] maxRC2 = getMaxRowCol(FO);
            int maxR = maxRC2[0], maxC = maxRC2[1];
            RArreglado = new ArrayList<>(Arrays.asList(R));
            nuevaFO = FO;

            if (difer > 0) {
                // agregar columnas numéricas: maxC+1 ... maxC+difer
                for (int k = 1; k <= difer; k++) {
                    int newCol = maxC + k;
                    String newColStr = String.format("%0" + (idx/2) + "d", newCol);
                    for (String fila : filas) {
                        String var = "x" + fila + newColStr;
                        nuevaFO = addZeroVarToFO(nuevaFO, var);
                    }
                    // agregar restricción columna (sum_i x(i,newCol)=1)
                    StringBuilder sb = new StringBuilder();
                    boolean first = true;
                    for (String fila : filas) {
                        if (!first) sb.append(" + ");
                        sb.append("x").append(fila).append(newColStr);
                        first = false;
                    }
                    sb.append(" = 1");
                    RArreglado.add(sb.toString());
                }
            } else {
                // agregar filas numéricas
                int need = -difer;
                for (int k = 1; k <= need; k++) {
                    int newRow = maxR + k;
                    String newRowStr = String.format("%0" + (idx/2) + "d", newRow);
                    for (String col : cols) {
                        String var = "x" + newRowStr + col;
                        nuevaFO = addZeroVarToFO(nuevaFO, var);
                    }
                    // agregar restricción fila (sum_j x(newRow,j)=1)
                    StringBuilder sb = new StringBuilder();
                    boolean first = true;
                    for (String col : cols) {
                        if (!first) sb.append(" + ");
                        sb.append("x").append(newRowStr).append(col);
                        first = false;
                    }
                    sb.append(" = 1");
                    RArreglado.add(sb.toString());
                }
            }

            setFO(nuevaFO);
            setR(RArreglado.toArray(new String[0]));
            return true;

        default:
            return false;
    }
}

    
    // Devuelve el par (maxFilaIndex, maxColIndex) leyendo subíndices numéricos x(ij)
private int[] getMaxRowCol(String FO) {
    Pattern varPattern = Pattern.compile("x(\\d+)");
    Matcher m = varPattern.matcher(FO);
    int idxLen = -1;
    Set<String> filas = new HashSet<>(), cols = new HashSet<>();
    while (m.find()) {
        String digits = m.group(1);
        if (idxLen == -1) idxLen = digits.length();
        if (digits.length() != idxLen) continue;
        int subLen = idxLen/2;
        String a = digits.substring(0, subLen);
        String b = digits.substring(subLen);
        filas.add(a); cols.add(b);
    }
    int maxRow = filas.stream().mapToInt(s -> Integer.parseInt(s)).max().orElse(0);
    int maxCol = cols.stream().mapToInt(s -> Integer.parseInt(s)).max().orElse(0);
    return new int[]{maxRow, maxCol, (idxLen==-1?0:idxLen)};
}

// Convierte un LHS en su negado: cambia signos de términos de forma segura.
// Ej: "3x11 - x12 + 5x13" -> "-3x11 + x12 - 5x13"
private String negateLHS(String lhs) {
    // añadir + delante si no tiene signo para facilitar reemplazos
    lhs = lhs.trim();
    if (lhs.length()==0) return lhs;
    if (!(lhs.charAt(0)=='+' || lhs.charAt(0)=='-')) lhs = "+" + lhs;
    // swap '+' and '-' safely
    lhs = lhs.replace("+", "##PLUS##");
    lhs = lhs.replace("-", "+");
    lhs = lhs.replace("##PLUS##", "-");
    // cleanup spaces
    return lhs.replaceAll("\\s+", " ").trim();
}

// Añade variable a FO con coef 0 (evita problemas de parseo)
private String addZeroVarToFO(String FO, String varName) {
    FO = (FO == null) ? "" : FO.trim();
    if (!FO.endsWith(" ") && FO.length()>0) FO += " ";
    // ejemplo: "+ 0x123"
    return FO + "+ 0" + varName;
}


    public String getFO() {
        return this.Fo;
    }

    public void setFO(String FO) {
        this.Fo = FO;
    }

    public String[] getR() {
        return this.R;
    }

    public void setR(String[] R) {
        this.R = R;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlgoritmoBox;
    private javax.swing.JButton CalcButton;
    private SubIndiceTextPane ObjetiveFunction;
    private SubIndiceTextPane Restrictions;
    private javax.swing.JComboBox<String> ZType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
